trigger:
    branches:
        include:
            - main
            - master
            - 蜒枛遫€〒䡫d
            - 丂丄丅丆丏丒丟
            - ⿷⿸⿹⿺⿻
            - 龡D4☆★○●◎◇◆□■△▲※

    paths:
        include:
            - "*蜒枛遫€〒??.txt"
            - "*⿷⿸⿹⿺?.txt"

pool: Default

steps:
- script: echo 蜒枛遫€〒䡫d.txt 文件更改啦！
  displayName: '癌蔼矮艾碍爱隘鼾D2丠両狛丣囆囇囈囉囋D3狜狝狟㥮狢狤狥狦D4ˇ¨〃々—～D1∟∣≒≧⊿═║D5U1U2U3㐈㐉㐊㩴'